import { type KPattern, type KPuzzle, KTransformation } from "cubing/kpuzzle";
import type { PuzzleGeometry } from "cubing/puzzle-geometry";
import { type Perm, PermutationGroup } from "./schreier-sims";
import { isRotationName, type SetOmission } from "./twsearch-state";
import type { StickerModel } from "./sticker-colors";

// Whether a pattern can be reached with the puzzle's moves, on the orbits
// whose pieces are fully distinguishable by their colors (other orbits are
// only count-checked, in sticker-colors.ts).
//
// Each such orbit contributes one point per (location, twist), or one per
// location when twists can't be seen.  A transformation becomes the
// permutation of these points it induces; the state is reachable on these
// orbits exactly when its permutation is in the group generated by the
// moves' permutations (checked with Schreier-Sims).

export type Reachability = "reachable" | "rotated" | "unreachable";

interface Layout {
  orbit: string;
  offset: number;
  m: number; // points per location (1 if twists aren't visible)
  n: number;
  mod: number; // the orbit's orientation count
}

function toPerm(
  layouts: Layout[],
  degree: number,
  data: Record<string, { perm: number[]; delta: number[] }>,
): Perm {
  const perm = new Array<number>(degree);
  for (const { orbit, offset, m, n, mod } of layouts) {
    const { perm: p, delta } = data[orbit];
    for (let i = 0; i < n; i++) {
      const d = ((delta[i] % mod) + mod) % mod;
      for (let w = 0; w < m; w++) {
        // A piece at location p[i] with twist w arrives at i with twist w+d.
        perm[offset + p[i] * m + w] = offset + i * m + (m === 1 ? 0 : (w + d) % m);
      }
    }
  }
  return perm;
}

export class ReachabilityChecker {
  #layouts: Layout[] = [];
  #degree = 0;
  #moves: PermutationGroup;
  #withRotations: PermutationGroup;

  /**
   * @param moves the transformations of the moves twsearch uses
   * @param rotations the transformations of whole-puzzle rotations
   * @param omission what twsearch is told to ignore (by orbit name); ignored
   *   orbits (or their permutations) and ignored twists aren't checked
   */
  constructor(
    model: StickerModel,
    moves: KTransformation[],
    rotations: KTransformation[],
    omission: SetOmission = () => 0,
  ) {
    for (const orbit of model.orbits) {
      const ignore = omission(orbit.name);
      if (!orbit.positionsDistinguishable || ignore & 1) continue;
      const m = orbit.twistsVisible && !(ignore & 2) ? orbit.numOrientations : 1;
      this.#layouts.push({ orbit: orbit.name, offset: this.#degree, m, n: orbit.numPieces, mod: orbit.numOrientations });
      this.#degree += orbit.numPieces * m;
    }
    const fromTransformation = (t: KTransformation) =>
      toPerm(
        this.#layouts,
        this.#degree,
        Object.fromEntries(
          this.#layouts.map(({ orbit }) => {
            const o = t.transformationData[orbit];
            return [orbit, { perm: o.permutation, delta: o.orientationDelta }];
          }),
        ),
      );
    const movePerms = moves.map(fromTransformation);
    this.#moves = new PermutationGroup(movePerms, this.#degree);
    this.#withRotations = new PermutationGroup(
      [...movePerms, ...rotations.map(fromTransformation)],
      this.#degree,
    );
  }

  /** Orbits the check covers. */
  get orbits(): string[] {
    return this.#layouts.map((l) => l.orbit);
  }

  check(pattern: KPattern): Reachability {
    if (this.#degree === 0) return "reachable";
    const p = toPerm(
      this.#layouts,
      this.#degree,
      Object.fromEntries(
        this.#layouts.map(({ orbit }) => {
          const o = pattern.patternData[orbit];
          return [orbit, { perm: o.pieces, delta: o.orientation }];
        }),
      ),
    );
    if (this.#moves.contains(p)) return "reachable";
    return this.#withRotations.contains(p) ? "rotated" : "unreachable";
  }
}

/**
 * The puzzle's whole-puzzle rotations as transformations on the Explorer's
 * KPuzzle, taken from PuzzleGeometry's own definition (internal names).  They
 * are not looked up by name in the Explorer's KPuzzle: its notation renames
 * moves, and a rotation's name there can be a different rotation.
 */
export function rotationTransformations(pg: PuzzleGeometry, kpuzzle: KPuzzle): KTransformation[] {
  return Object.entries(pg.getKPuzzleDefinition(true).moves)
    .filter(([name]) => isRotationName(name))
    .map(([, data]) => new KTransformation(kpuzzle, data));
}
