// Schreier-Sims with a membership test.
//
// A port of cubing.js's puzzle-geometry/SchreierSims.ts (Knuth's variant),
// which exposes only the group order; here the stabilizer chain is kept so
// that permutations can be tested for membership.  Permutations are arrays,
// multiplied as in cubing.js's Perm: mul(a, b)[i] = b[a[i]].

export type Perm = number[];

function mul(a: Perm, b: Perm): Perm {
  const c = new Array<number>(a.length);
  for (let i = 0; i < a.length; i++) {
    c[i] = b[a[i]];
  }
  return c;
}

function inv(a: Perm): Perm {
  const c = new Array<number>(a.length);
  for (let i = 0; i < a.length; i++) {
    c[a[i]] = i;
  }
  return c;
}

export class PermutationGroup {
  readonly degree: number;
  // sgs[k][j], if present, maps point k to j and fixes every point above k.
  #sgs: (Perm | undefined)[][] = [];
  #sgsi: (Perm | undefined)[][] = [];
  #tk: Perm[][] = [];

  /** The group generated by `generators`, all of the same degree. */
  constructor(generators: Perm[], degree = generators[0]?.length ?? 0) {
    this.degree = degree;
    const e = [...Array(degree).keys()];
    for (let i = 0; i < degree; i++) {
      this.#sgs.push([]);
      this.#sgsi.push([]);
      this.#tk.push([]);
      this.#sgs[i][i] = e;
      this.#sgsi[i][i] = e;
    }
    for (const g of generators) {
      if (degree > 0) {
        this.#knutha(degree - 1, g);
      }
    }
  }

  /** Whether p is in the group. */
  contains(p: Perm): boolean {
    if (p.length !== this.degree) {
      throw new Error("permutation has the wrong degree");
    }
    for (let i = p.length - 1; i >= 0; i--) {
      const j = p[i];
      if (j !== i) {
        const s = this.#sgsi[i][j];
        if (!s) {
          return false;
        }
        p = mul(p, s);
      }
    }
    return true;
  }

  /** The order of the group. */
  order(): bigint {
    let size = 1n;
    for (const row of this.#sgs) {
      size *= BigInt(row.filter(Boolean).length);
    }
    return size;
  }

  #knutha(k: number, p: Perm): void {
    this.#tk[k].push(p);
    for (let i = 0; i < this.#sgs[k].length; i++) {
      const s = this.#sgs[k][i];
      if (s) {
        this.#knuthb(k, mul(s, p));
      }
    }
  }

  #knuthb(k: number, p: Perm): void {
    const j = p[k];
    if (!this.#sgs[k][j]) {
      this.#sgs[k][j] = p;
      this.#sgsi[k][j] = inv(p);
      for (const t of this.#tk[k]) {
        this.#knuthb(k, mul(p, t));
      }
      return;
    }
    const p2 = mul(p, this.#sgsi[k][j]!);
    if (!this.contains(p2)) {
      this.#knutha(k - 1, p2);
    }
  }
}
